--------------------------------------------------------
--  File created - Wednesday-August-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "NIKHIL"."ADDRESS" 
   (	"ID" NUMBER(10,0), 
	"ADDRESS" VARCHAR2(255 CHAR), 
	"CREATED_DATE" TIMESTAMP (6), 
	"FIRSTNAME" VARCHAR2(255 CHAR), 
	"LASTNAME" VARCHAR2(255 CHAR), 
	"LASTUPDATE_DATE" TIMESTAMP (6), 
	"POSTALCODE" NUMBER(10,0), 
	"TYPE" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into NIKHIL.ADDRESS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C0011816
--------------------------------------------------------

  CREATE UNIQUE INDEX "NIKHIL"."SYS_C0011816" ON "NIKHIL"."ADDRESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "NIKHIL"."ADDRESS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NIKHIL"."ADDRESS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "NIKHIL"."ADDRESS" MODIFY ("POSTALCODE" NOT NULL ENABLE);
  ALTER TABLE "NIKHIL"."ADDRESS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "NIKHIL"."ADDRESS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "NIKHIL"."ADDRESS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "NIKHIL"."ADDRESS" MODIFY ("ID" NOT NULL ENABLE);
