--------------------------------------------------------
--  File created - Wednesday-August-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERS_PRODUCT
--------------------------------------------------------

  CREATE TABLE "NIKHIL"."ORDERS_PRODUCT" 
   (	"ORDER_ID" NUMBER(10,0), 
	"PRODUCT_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into NIKHIL.ORDERS_PRODUCT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index UK_GCT83I6VLIH0RFSSNNF1ADC16
--------------------------------------------------------

  CREATE UNIQUE INDEX "NIKHIL"."UK_GCT83I6VLIH0RFSSNNF1ADC16" ON "NIKHIL"."ORDERS_PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDERS_PRODUCT
--------------------------------------------------------

  ALTER TABLE "NIKHIL"."ORDERS_PRODUCT" ADD CONSTRAINT "UK_GCT83I6VLIH0RFSSNNF1ADC16" UNIQUE ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NIKHIL"."ORDERS_PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "NIKHIL"."ORDERS_PRODUCT" MODIFY ("ORDER_ID" NOT NULL ENABLE);
