--------------------------------------------------------
--  File created - Wednesday-August-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT_CATEGORY
--------------------------------------------------------

  CREATE TABLE "NIKHIL"."PRODUCT_CATEGORY" 
   (	"ID" NUMBER(10,0), 
	"CODE" VARCHAR2(255 CHAR), 
	"CREATED_DATE" TIMESTAMP (6), 
	"ENABLED" NUMBER(1,0), 
	"LASTUPDATE_DATE" TIMESTAMP (6), 
	"TYPE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into NIKHIL.PRODUCT_CATEGORY
SET DEFINE OFF;
Insert into NIKHIL.PRODUCT_CATEGORY (ID,CODE,CREATED_DATE,ENABLED,LASTUPDATE_DATE,TYPE) values (6,'Computers&Laptops',to_timestamp('08-08-18 10:50:28.804000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1,null,'Computers & Laptops');
Insert into NIKHIL.PRODUCT_CATEGORY (ID,CODE,CREATED_DATE,ENABLED,LASTUPDATE_DATE,TYPE) values (7,'Cameras&Photos',to_timestamp('08-08-18 10:50:28.805000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1,null,'Cameras & Photos');
Insert into NIKHIL.PRODUCT_CATEGORY (ID,CODE,CREATED_DATE,ENABLED,LASTUPDATE_DATE,TYPE) values (8,'Hardware',to_timestamp('08-08-18 10:50:28.805000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1,null,'Hardware');
Insert into NIKHIL.PRODUCT_CATEGORY (ID,CODE,CREATED_DATE,ENABLED,LASTUPDATE_DATE,TYPE) values (9,'Smartphones&Tablets',to_timestamp('08-08-18 10:50:28.806000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1,null,'Smartphones & Tablets');
Insert into NIKHIL.PRODUCT_CATEGORY (ID,CODE,CREATED_DATE,ENABLED,LASTUPDATE_DATE,TYPE) values (10,'TV&Audio',to_timestamp('08-08-18 10:50:28.806000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1,null,'TV & Audio');
Insert into NIKHIL.PRODUCT_CATEGORY (ID,CODE,CREATED_DATE,ENABLED,LASTUPDATE_DATE,TYPE) values (11,'Gadgets',to_timestamp('08-08-18 10:50:28.807000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1,null,'Gadgets');
Insert into NIKHIL.PRODUCT_CATEGORY (ID,CODE,CREATED_DATE,ENABLED,LASTUPDATE_DATE,TYPE) values (12,'Car&Electronics',to_timestamp('08-08-18 10:50:28.807000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1,null,'Car & Electronics');
Insert into NIKHIL.PRODUCT_CATEGORY (ID,CODE,CREATED_DATE,ENABLED,LASTUPDATE_DATE,TYPE) values (13,'VideoGames&Consoles',to_timestamp('08-08-18 10:50:28.807000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1,null,'Video Games & Consoles');
Insert into NIKHIL.PRODUCT_CATEGORY (ID,CODE,CREATED_DATE,ENABLED,LASTUPDATE_DATE,TYPE) values (14,'Accessories',to_timestamp('08-08-18 10:50:28.808000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1,null,'Accessories');
--------------------------------------------------------
--  DDL for Index SYS_C0011837
--------------------------------------------------------

  CREATE UNIQUE INDEX "NIKHIL"."SYS_C0011837" ON "NIKHIL"."PRODUCT_CATEGORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_C4MVV9OR7VACPH0GGKTTMY252
--------------------------------------------------------

  CREATE UNIQUE INDEX "NIKHIL"."UK_C4MVV9OR7VACPH0GGKTTMY252" ON "NIKHIL"."PRODUCT_CATEGORY" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_25XJEIO8M41WF2OELAC29YKR6
--------------------------------------------------------

  CREATE UNIQUE INDEX "NIKHIL"."UK_25XJEIO8M41WF2OELAC29YKR6" ON "NIKHIL"."PRODUCT_CATEGORY" ("TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT_CATEGORY
--------------------------------------------------------

  ALTER TABLE "NIKHIL"."PRODUCT_CATEGORY" ADD CONSTRAINT "UK_25XJEIO8M41WF2OELAC29YKR6" UNIQUE ("TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NIKHIL"."PRODUCT_CATEGORY" ADD CONSTRAINT "UK_C4MVV9OR7VACPH0GGKTTMY252" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NIKHIL"."PRODUCT_CATEGORY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NIKHIL"."PRODUCT_CATEGORY" MODIFY ("ENABLED" NOT NULL ENABLE);
  ALTER TABLE "NIKHIL"."PRODUCT_CATEGORY" MODIFY ("ID" NOT NULL ENABLE);
