--------------------------------------------------------
--  File created - Wednesday-August-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "NIKHIL"."USERS" 
   (	"ID" NUMBER(10,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"ENABLED" NUMBER(1,0), 
	"FIRSTNAME" VARCHAR2(255 CHAR), 
	"LASTUPDATE_DATE" TIMESTAMP (6), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"ROLE" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into NIKHIL.USERS
SET DEFINE OFF;
Insert into NIKHIL.USERS (ID,CREATED_DATE,EMAIL,ENABLED,FIRSTNAME,LASTUPDATE_DATE,PASSWORD,ROLE,USERNAME) values (3,to_timestamp('08-08-18 10:50:28.757000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),null,1,'Nikhil Mohandas',null,'$2a$12$LtbYtEzOBdnsiD/E9Wtj2OnpJ1FB7girEHgGVhynqGSFVKGazltGO','ROLE_ADMIN','nikhil');
--------------------------------------------------------
--  DDL for Index SYS_C0011845
--------------------------------------------------------

  CREATE UNIQUE INDEX "NIKHIL"."SYS_C0011845" ON "NIKHIL"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "NIKHIL"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NIKHIL"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "NIKHIL"."USERS" MODIFY ("ENABLED" NOT NULL ENABLE);
  ALTER TABLE "NIKHIL"."USERS" MODIFY ("ID" NOT NULL ENABLE);
